# Generated by Django 3.0.5 on 2020-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/')),
                ('author_img', models.ImageField(default='blog/', upload_to='blog/')),
                ('date', models.DateTimeField()),
                ('category', models.CharField(default='Unknown', max_length=80)),
                ('summary', models.CharField(max_length=80)),
                ('company', models.CharField(default='Unknown', max_length=80)),
                ('text', models.TextField(max_length=200)),
                ('Comment', models.IntegerField(default=1)),
                ('blogger', models.CharField(default='Unknown', max_length=80)),
                ('facebook_link', models.CharField(default='https://www.facebook.com/tickabrand/', max_length=80)),
                ('insta_link', models.CharField(default='https://www.instagram.com/tickabrand/', max_length=80)),
            ],
        ),
    ]
