# Generated by Django 3.0.5 on 2020-06-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add',
            new_name='Adver',
        ),
    ]
