# Generated by Django 3.0.5 on 2020-06-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_auto_20200617_0914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adver',
            new_name='Billboard',
        ),
    ]
