# Generated by Django 3.0.5 on 2020-06-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_auto_20200617_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='image',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
