# Generated by Django 3.0.5 on 2020-06-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_auto_20200617_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='Areacoverd',
            field=models.CharField(default='Fotress', max_length=30),
        ),
        migrations.AddField(
            model_name='billboard',
            name='Category',
            field=models.CharField(default='Outdoor', max_length=30),
        ),
        migrations.AddField(
            model_name='billboard',
            name='Phone',
            field=models.CharField(default='+92', max_length=30),
        ),
        migrations.AddField(
            model_name='billboard',
            name='availability',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='billboard',
            name='facelink',
            field=models.CharField(default='http://', max_length=30),
        ),
        migrations.AddField(
            model_name='billboard',
            name='instalink',
            field=models.CharField(default='http://', max_length=30),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
