# Generated by Django 3.0.5 on 2020-06-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0006_auto_20200617_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
