# Generated by Django 3.0.5 on 2020-06-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0007_billboard_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outdoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='', max_length=300)),
                ('Category', models.CharField(default='Outdoor', max_length=30)),
                ('price', models.IntegerField(default=500)),
                ('availability', models.CharField(default='Available', max_length=50)),
                ('Phone', models.CharField(default='+92', max_length=30)),
                ('Areacoverd', models.CharField(default='Fotress', max_length=30)),
                ('facebook', models.CharField(default='http://', max_length=30)),
                ('insta', models.CharField(default='http://', max_length=30)),
            ],
        ),
    ]
