# Generated by Django 3.0.5 on 2020-07-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0008_outdoor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='Areacoverd',
            field=models.CharField(default='Fotress', max_length=100),
        ),
    ]
