# Generated by Django 3.0.5 on 2020-07-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0011_billboard_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='outdoor',
            name='Company',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='outdoor',
            name='Medium',
            field=models.CharField(default='Print Medium', max_length=60),
        ),
        migrations.AlterField(
            model_name='outdoor',
            name='Areacoverd',
            field=models.CharField(default='Fotress', max_length=100),
        ),
    ]
