# Generated by Django 3.0.5 on 2020-07-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0012_auto_20200708_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='description',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='outdoor',
            name='description',
            field=models.TextField(default='', max_length=600),
        ),
    ]
