# Generated by Django 3.0.5 on 2020-08-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0013_auto_20200708_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='facebook',
            field=models.CharField(default='https://www.facebook.com/EyeAdvert-111649233951911', max_length=30),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='insta',
            field=models.CharField(default='https://www.instagram.com/?hl=en', max_length=30),
        ),
        migrations.AlterField(
            model_name='outdoor',
            name='facebook',
            field=models.CharField(default='https://www.facebook.com/EyeAdvert-111649233951911', max_length=30),
        ),
        migrations.AlterField(
            model_name='outdoor',
            name='insta',
            field=models.CharField(default='https://www.instagram.com/?hl=en', max_length=30),
        ),
    ]
