# Generated by Django 3.0.5 on 2020-06-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
                ('summary', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=10000)),
            ],
        ),
    ]
