# Generated by Django 3.0.5 on 2020-06-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='currency',
            field=models.CharField(default='Rs', max_length=20),
        ),
    ]
