# Generated by Django 3.0.5 on 2020-06-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_recommend_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='price',
        ),
    ]
